default_language_version:
  python: python3.12

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.11
  hooks:
  - id: ruff
    args: [ --fix, --exit-non-zero-on-fix ]

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.12.1
  hooks:
  - id: black
    args: ['--config=pyproject.toml']

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    language: system
    exclude: '^tests/'

- repo: https://github.com/pdm-project/pdm
  rev: 2.11.2
  hooks:
  - id: pdm-lock-check
    name: pdm lock check
  - id: pdm-export
    name: pdm export
    args: ['-o', 'requirements.txt', '--prod', '--without-hashes']
    files: ^pdm.lock$
    always_run: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
    name: check large files
    args: ['--maxkb=1024']
  - id: check-toml
  - id: check-yaml
  - id: check-json
  - id: end-of-file-fixer
    name: fix eof newline
    types_or: [python, yaml, toml]
  - id: no-commit-to-branch
    name: protect master branch
